# syntax=docker/dockerfile:1

FROM python:3

WORKDIR /app

COPY src/ .

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_ENV=production

RUN mkdir out/ && mkdir uploads/
RUN apt update && apt install -y libsndfile1
RUN pip3 install -r requirements.txt

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8080"]