# syntax=docker/dockerfile:1

FROM fhoerst/deepxi:latest

WORKDIR /DeepXi

COPY src/ .

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_ENV=production

RUN rm /DeepXi/set/test_noisy_speech/FB_FB10_07_voice-babble_5dB.wav
RUN pip3 install -r requirements.txt

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8080"]
