# syntax=docker/dockerfile:1

FROM nvcr.io/nvidia/cuda
#FROM nvcr.io/nvidia/maxine/maxine-audioeffects-sdk:1.0.5

WORKDIR /app

RUN apt update && apt install sox python3-pip curl -y
RUN curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.pbmm
RUN curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.scorer

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_ENV=production

RUN mkdir out/ && mkdir uploads/
RUN apt install libcudart10.1 libcusparse10 libcusolver10 libcublas10 -y
RUN pip3 --version
COPY libcudnn7_7.6.5.32-1+cuda10.2_amd64.deb .
RUN apt install ./libcudnn7_7.6.5.32-1+cuda10.2_amd64.deb
COPY src/ .
RUN pip3 install -r requirements.txt

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8080"]
